file_url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(file_url, destfile = "dataset.zip")
unzip("dataset.zip")
library(dplyr)
features <- read.table("UCI HAR Dataset/features.txt", header = FALSE)
activity_labels <- read.table("UCI HAR Dataset/activity_labels.txt", header = FALSE)
subject_train <- read.table("UCI HAR Dataset/train/subject_train.txt", header = FALSE)
subject_test <- read.table("UCI HAR Dataset/test/subject_test.txt", header = FALSE)
subject <- rbind(subject_train, subject_test)
y_train <- read.table("UCI HAR Dataset/train/y_train.txt", header = FALSE)
y_test <- read.table("UCI HAR Dataset/test/y_test.txt", header = FALSE)
y <- rbind(y_train, y_test)
X_train <- read.table("UCI HAR Dataset/train/X_train.txt", header = FALSE)
X_test <- read.table("UCI HAR Dataset/test/X_test.txt", header = FALSE)
x <- rbind(X_train, X_test)
 names(x) <- features$V2
 mean_std_cols<- grep("-(mean|std)\\(\\)", features$V2)
 x_sub <- x[, mean_std_cols]
 data <- cbind(subject, y, x_sub)
 names(data)[1:2] <- c("subject", "activity")
 data$activity <- activity_labels[data$activity, 2]
 names(data) <- gsub("^t", "Time", names(data))
 names(data) <- gsub("^f", "Frequency", names(data))
 names(data) <- gsub("Acc", "Accelerometer", names(data))
 names(data) <- gsub("Gyro", "Gyroscope", names(data))
 names(data) <- gsub("mean\\(\\)", "Mean", names(data))
 names(data) <- gsub("std\\(\\)", "Std", names(data))
 tidy_data <- data %>% group_by(subject, activity) %>% summarise(across(everything(), mean), .groups = "drop")
 write.table(tidy_data, file = "tidy_data_average.txt", row.names = FALSE)