file_url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(file_url, destfile = "dataset.zip")
unzip("dataset.zip")
library(dplyr)
features <- read.table("UCI HAR Dataset/features.txt")
activity_labels <- read.table("UCI HAR Dataset/activity_labels.txt")
subject_train <- read.table("UCI HAR Dataset/train/subject_train.txt")
subject_test <- read.table("UCI HAR Dataset/test/subject_test.txt")
subject <- rbind(subject_train, subjecty_test)
y_train <- read.table("UCI HAR Dataset/train/y_train.txt")
y_test <- read.table("UCI HAR Dataset/test/y_test.txt")
y <- rbind(y_train, y_test)
x_train <- read.table("UCI HAR Dataset/train/x_train.txt")
x_test <- read.table("UCI HAR Dataset/test/x_test.txt")
x <- rbind(x_train, x_test)
 names(x) <- features$V2
 mean_std_cols<- grep("-(mean|std)\\(\\)", features$V2)
 x_sub <- x[, mean_std_cols]
 data <- cbind(subject, y, x_sub)
 names(data)[1:2] <- c("subject", "activity")
 data$activity <- activity_labels[data$activity, 2]
 names(data) <- gsub("^t", "Time", names(data))
 names(data) <- gsub("^f", "Freq", names(data))
 names(data) <- gsub("Acc", "Accelerometer", names(data))
 names(data) <- gsub("Gyro", "Gyroscope", names(data))
 names(data) <- gsub("mean\\(\\)", "Mean", names(data))
 names(data) <- gsub("std\\(\\)", "Std", names(data))
 tidy_data <- data %>% group_by(subject, activity) %>% summarise(across(everything(), mean))
 write.table(tidy_data, "tidy_data_average.txt", row.names = FALSE)